name: Update wiki
on:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update wiki
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan github.com > ~/.ssh/known_hosts

          git clone --bare git@github.com:winapps-org/docs.git
          git -C docs.git push --mirror git@github.com:winapps-org/winapps.wiki.git
        env:
          DEPLOY_KEY: "${{ secrets.DEPLOY_KEY }}"

